version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8002:8000"
    links:
      - geth
  
  geth:
    build:
      context: ./docker-geth
    volumes:
      - ./docker-geth/ethereum:/home/geth-user
    environment:
      - "EXTERNAL_IP=${EXTERNAL_IP}"
    entrypoint: ["/bin/bash", "/home/geth-user/init-and-start-geth.sh"]
    ports:
      - "8545:8545"
